# Setup
title:            Cool<br>Request
tagline:          'A blog about Software, the Universe and Everything'
description:      'A blog about Software, the Universe and Everything'
url:              https://coolrequest.dev
#baseurl:          /
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
